In [16]:
install.packages("RSQLite")
install.packages("DBI")

library(RSQLite)
library(DBI)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [17]:
library(readr)

customers <- read_csv("customers.csv")
orders <- read_csv("orders.csv")
deliveries <- read_csv("deliveries.csv")
drivers <- read_csv("drivers.csv")
vehicles <- read_csv("vehicles.csv")
hubs <- read_csv("hubs.csv")
complaints <- read_csv("complaints.csv")
incidents <- read_csv("incidents.csv")
app_events <- read_csv("app_events.csv")

Rows: 650 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): customer_id, home_zone, customer_type, preferred_channel, account_...
dbl  (3): age, loyalty_score, app_engagement_score
dttm (1): signup_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1250 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): order_id, customer_id, service_type, pickup_zone, dropoff_zone, pr...
dbl  (3): promised_window_hours, order_value, special_handling_flag
dttm (1): order_created_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 950 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (6): delivery_id, order_id, driver_id, vehicle_id, hub_id, delivery_status
dbl  (5): route_distance_km, manual_route_override_count, proof_of_completio...
dttm (2): dispatch_time, delivery_completed_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 170 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): driver_id, base_zone, employment_type, shift_preference
dbl (4): years_experience, training_score, driver_rating, active_flag

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 120 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): vehicle_id, vehicle_type, assigned_zone, maintenance_status, telem...
dbl  (2): battery_health_pct, odometer_km
dttm (1): commission_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): hub_id, hub_name, zone, hub_type
dbl (1): capacity_score

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 320 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): complaint_id, customer_id, order_id, complaint_type, channel, seve...
dbl  (2): resolution_days, compensation_amount
dttm (1): created_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 280 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): incident_id, delivery_id, incident_type, severity, resolution_status
dbl  (1): resolved_hours
dttm (1): reported_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 640 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): event_id, customer_id, order_id, event_type, session_id, device_ty...
dbl  (2): api_latency_ms, success_flag
dttm (1): event_timestamp

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [18]:
library(DBI)
library(RSQLite)

# Creating SQLite database connection
con <- dbConnect(SQLite(), "northstar_sql.db")

# Copying R data frames into SQLite tables
dbWriteTable(con, "customers", customers, overwrite = TRUE)
dbWriteTable(con, "orders", orders, overwrite = TRUE)
dbWriteTable(con, "deliveries", deliveries, overwrite = TRUE)
dbWriteTable(con, "drivers", drivers, overwrite = TRUE)
dbWriteTable(con, "vehicles", vehicles, overwrite = TRUE)
dbWriteTable(con, "hubs", hubs, overwrite = TRUE)
dbWriteTable(con, "complaints", complaints, overwrite = TRUE)
dbWriteTable(con, "incidents", incidents, overwrite = TRUE)
dbWriteTable(con, "app_events", app_events, overwrite = TRUE)

# Check tables created
dbListTables(con)

[1] "app_events" "complaints" "customers"  "deliveries" "drivers"
[6] "hubs"       "incidents"  "orders"     "vehicles"

In [19]:
dbGetQuery(con, "
SELECT *
FROM deliveries
LIMIT 10
")

   delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1  DL00001     O00938   D004      V056       H05    1718708220
2  DL00002     O00004   D138      V007       H02    1736621100
3  DL00003     O00639   D006      V049       H02    1748896740
4  DL00004     O00313   D116      V055       H02    1709940660
5  DL00005     O00844   D108      V034       H01    1758454980
6  DL00006     O00029   D037      V098       H03    1726058400
7  DL00007     O00097   D151      V037       H07    1704807660
8  DL00008     O00207   D082      V066       H03    1724362440
9  DL00009     O00297   D088      V029       H05    1712957580
10 DL00010     O00836   D058      V057       H08    1758568140
   delivery_completed_at delivery_status route_distance_km
1  1718787960            Failed          17.26
2  1736617140            OnTime          10.34
3  1748900732            OnTime           7.92
4  1710027008            Delayed         16.42
5  1758469534            OnTime          14.52
6  1726161112            Delayed         13.84
7  1704929951            Delayed         32.72
8  1724368942            OnTime           7.16
9  1712971133            OnTime          40.23
10 1758590129            Failed           9.85
   manual_route_override_count proof_of_completion_missing
1  1                           0
2  1                           0
3  0                           0
4  0                           0
5  1                           0
6  0                           0
7  0                           0
8  1                           0
9  1                           0
10 1                           0
   customer_rating_post_delivery fuel_or_charge_cost
1  3.07                          12.05
2  5.00                          13.41
3  4.98                           8.51
4  4.18                          13.62
5  4.18                           9.22
6  1.57                           9.58
7  4.64                          17.70
8  3.76                          11.66
9  3.70                          15.78
10 3.20                           9.31

In [20]:
dbGetQuery(con, "
SELECT delivery_id,
       delivery_status,
       route_distance_km,
       manual_route_override_count
FROM deliveries
WHERE delivery_status = 'Delayed'
LIMIT 10
")

   delivery_id delivery_status route_distance_km manual_route_override_count
1  DL00004     Delayed         16.42             0
2  DL00006     Delayed         13.84             0
3  DL00007     Delayed         32.72             0
4  DL00017     Delayed         20.79             0
5  DL00028     Delayed         15.53             2
6  DL00034     Delayed         14.68             0
7  DL00048     Delayed          7.37             0
8  DL00052     Delayed         26.38             1
9  DL00054     Delayed         29.80             1
10 DL00055     Delayed         35.07             5

In [21]:
dbGetQuery(con, "
PRAGMA table_info(deliveries)
")

   cid name                          type notnull dflt_value pk
1   0  delivery_id                   TEXT 0       NA         0
2   1  order_id                      TEXT 0       NA         0
3   2  driver_id                     TEXT 0       NA         0
4   3  vehicle_id                    TEXT 0       NA         0
5   4  hub_id                        TEXT 0       NA         0
6   5  dispatch_time                 REAL 0       NA         0
7   6  delivery_completed_at         REAL 0       NA         0
8   7  delivery_status               TEXT 0       NA         0
9   8  route_distance_km             REAL 0       NA         0
10  9  manual_route_override_count   REAL 0       NA         0
11 10  proof_of_completion_missing   REAL 0       NA         0
12 11  customer_rating_post_delivery REAL 0       NA         0
13 12  fuel_or_charge_cost           REAL 0       NA         0

In [22]:
dbGetQuery(con, "
SELECT delivery_id,
       delivery_status,
       route_distance_km,
       manual_route_override_count
FROM deliveries
ORDER BY manual_route_override_count DESC
LIMIT 10
")

   delivery_id delivery_status route_distance_km manual_route_override_count
1  DL00473     OnTime          14.15             7
2  DL00055     Delayed         35.07             5
3  DL00085     OnTime           9.49             5
4  DL00374     OnTime          23.47             5
5  DL00672     OnTime          35.33             5
6  DL00744     Delayed         25.36             5
7  DL00881     Delayed         12.77             5
8  DL00922     Delayed         12.65             5
9  DL00019     OnTime          16.35             4
10 DL00021     OnTime           9.77             4

In [23]:
dbGetQuery(con, "
SELECT delivery_status,
       COUNT(*) AS total_deliveries
FROM deliveries
GROUP BY delivery_status
")

  delivery_status total_deliveries
1 Delayed         202
2 Failed          132
3 OnTime          616

In [24]:
dbGetQuery(con, "
SELECT delivery_status,
       AVG(route_distance_km) AS average_distance
FROM deliveries
GROUP BY delivery_status
")

  delivery_status average_distance
1 Delayed         14.67025
2 Failed          13.36530
3 OnTime          13.77636

In [25]:
dbGetQuery(con, "
SELECT d.delivery_id,
       d.delivery_status,
       d.hub_id,
       h.hub_name
FROM deliveries d
JOIN hubs h
ON d.hub_id = h.hub_id
LIMIT 10
")

   delivery_id delivery_status hub_id hub_name
1  DL00001     Failed          H05    Central Core
2  DL00002     OnTime          H02    South Link
3  DL00003     OnTime          H02    South Link
4  DL00004     Delayed         H02    South Link
5  DL00005     OnTime          H01    North Exchange
6  DL00006     Delayed         H03    East Dock
7  DL00007     Delayed         H07    Riverside Hub
8  DL00008     OnTime          H03    East Dock
9  DL00009     OnTime          H05    Central Core
10 DL00010     Failed          H08    Midtown Relay

In [26]:
dbGetQuery(con, "
SELECT h.hub_name,
       d.delivery_status,
       COUNT(*) AS total_deliveries
FROM deliveries d
JOIN hubs h
ON d.hub_id = h.hub_id
GROUP BY h.hub_name, d.delivery_status
ORDER BY total_deliveries DESC
")

   hub_name       delivery_status total_deliveries
1  North Exchange OnTime          93
2  East Dock      OnTime          85
3  West Gate      OnTime          83
4  Midtown Relay  OnTime          80
5  Riverside Hub  OnTime          76
6  South Link     OnTime          70
7  Central Core   OnTime          67
8  Airport Hub    OnTime          62
9  West Gate      Delayed         28
10 Airport Hub    Delayed         27
11 Midtown Relay  Failed          26
12 North Exchange Delayed         26
13 South Link     Delayed         26
14 Central Core   Delayed         25
15 Riverside Hub  Delayed         25
16 Central Core   Failed          23
17 East Dock      Delayed         23
18 Midtown Relay  Delayed         22
19 North Exchange Failed          17
20 West Gate      Failed          16
21 Airport Hub    Failed          15
22 Riverside Hub  Failed          14
23 East Dock      Failed          11
24 South Link     Failed          10

In [27]:
dbGetQuery(con, "
SELECT complaint_type,
       COUNT(*) AS total_complaints
FROM complaints
GROUP BY complaint_type
ORDER BY total_complaints DESC
")

  complaint_type    total_complaints
1 Delay             101
2 MissedPickup       64
3 AppIssue           53
4 DriverBehaviour    51
5 SupportExperience  20
6 Billing            16
7 Damage             15

In [28]:
dbGetQuery(con, "
SELECT h.hub_name,
       COUNT(*) AS total_delayed
FROM deliveries d
JOIN hubs h
ON d.hub_id = h.hub_id
WHERE d.delivery_status = 'Delayed'
GROUP BY h.hub_name
ORDER BY total_delayed DESC
LIMIT 5
")

  hub_name       total_delayed
1 West Gate      28
2 Airport Hub    27
3 South Link     26
4 North Exchange 26
5 Riverside Hub  25